window.alert("HI")
window.alert("Umm")
window.alert("May Sasabihin Ako Sayo")
window.alert("Wag Nalang Pala")
window.alert("Baka Magalit Ka")
window.alert("De Jk")
window.alert("Ito na Talaga")
window.alert("ummmm")
window.alert("ummmm")
window.alert("ummmm")
window.alert("Kinakabahan ako")
window.alert("Hahahahaha")
window.alert("Aughghhghghhh")
window.alert("Ang Cute Mo")
window.alert("Hahahahaah")
